/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package master;

import Control.Counter;
import Control.ImageSize;
import java.awt.event.ActionEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author yusuf
 */
public final class MenuJFrame extends javax.swing.JFrame {
    
     public void date(){

        Date d  =new Date();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");

        String dd = sdf.format(d);
//        jLabel2.setText(dd);
    }
     
     // time
    Timer t ;
    SimpleDateFormat st ;
    
    public void times(){
        
        t = new Timer(0, (ActionEvent e) -> {

            Date dt  =new Date();
            st = new SimpleDateFormat("hh:mm:ss a");
            String tt = st.format(dt);
            labelJam.setText(tt);
        });
        t.start();
    }


    /**
     * Creates new form MenuAdminJFrame
     */
    
    private void counter(){
        
        String user = Counter.countUser();
        String transaksi = Counter.countTransaksi();
        String[] trx = transaksi.split("\\s+");
        
        labelCountUser.setText(user);
        
        labelJmlTransaksi.setText(trx[0]);
        labelTransaksi.setText(trx[1] + " " +trx[2].replaceAll(",", "."));
        labelTerjual.setText(trx[3]);
        
    }
    
    private void setMenu(){
        try{
            if(Login.role2.equals("Admin")){
                jLayeredPanel.removeAll();
                jLayeredPanel.add(panelAdmin);
                jLayeredPanel.repaint();
                jLayeredPanel.revalidate();
            }else{
                jLayeredPanel.removeAll();
                jLayeredPanel.add(panelPetugas);
                jLayeredPanel.repaint();
                jLayeredPanel.revalidate();
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Anda Belum Login!");

           
        }
        
    }
    
    private void setLabel(){
//
        ImageSize.resizeImage(labelIcon);
        labelNama.setText(Login.nama);
    }
   
   
    public MenuJFrame() {
        initComponents();
       
        counter();
        date();
        
        times();
        setLabel();
        setMenu();

       
    }
    
    
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        judulAplikasi = new javax.swing.JLabel();
        panelDeveloper = new javax.swing.JLabel();
        labelJam = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();
        labelWelcome = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        jLayeredPanel = new javax.swing.JLayeredPane();
        panelAdmin = new javax.swing.JPanel();
        btnUser = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        panelPetugas = new javax.swing.JPanel();
        btnTransaksi = new javax.swing.JButton();
        btnBarang1 = new javax.swing.JButton();
        btnRiwayat1 = new javax.swing.JButton();
        panelRight = new javax.swing.JPanel();
        panelUser = new javax.swing.JPanel();
        labelCountUser = new javax.swing.JLabel();
        labelJumUser = new javax.swing.JLabel();
        panelTransaksi = new javax.swing.JPanel();
        labelTransaksi = new javax.swing.JLabel();
        labelJumTransaksi = new javax.swing.JLabel();
        panelJmlTransaksi = new javax.swing.JPanel();
        labelJmlTransaksi = new javax.swing.JLabel();
        tabeltotTransaksi = new javax.swing.JLabel();
        panelTerjual = new javax.swing.JPanel();
        labelTerjual = new javax.swing.JLabel();
        labelTextTerjual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        panelLeft.setBackground(new java.awt.Color(255, 255, 255));

        btnLogOut.setBackground(new java.awt.Color(255, 102, 102));
        btnLogOut.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(null);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setOpaque(true);
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
        });
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        judulAplikasi.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        judulAplikasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulAplikasi.setText("Aplikasi Kasir");

        panelDeveloper.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        panelDeveloper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelDeveloper.setText("By Sembagi Arutala");

        labelJam.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJam.setText("Label Jam");

        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/trolley-cart.png"))); // NOI18N
        labelIcon.setText("jLabel1");

        labelWelcome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelWelcome.setText("Welcome,");

        labelNama.setBackground(new java.awt.Color(28, 42, 57));
        labelNama.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama.setText("Nama");

        jLayeredPanel.setLayout(new java.awt.CardLayout());

        panelAdmin.setBackground(new java.awt.Color(255, 255, 255));

        btnUser.setBackground(new java.awt.Color(28, 42, 57));
        btnUser.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUser.setText("Data User");
        btnUser.setBorder(null);
        btnUser.setContentAreaFilled(false);
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.setOpaque(true);
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(28, 42, 57));
        btnBarang.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnBarang.setText("Data Barang");
        btnBarang.setBorder(null);
        btnBarang.setContentAreaFilled(false);
        btnBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarang.setOpaque(true);
        btnBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBarangMouseExited(evt);
            }
        });
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnRiwayat.setBackground(new java.awt.Color(28, 42, 57));
        btnRiwayat.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        btnRiwayat.setText("Riwayat");
        btnRiwayat.setBorder(null);
        btnRiwayat.setContentAreaFilled(false);
        btnRiwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRiwayat.setOpaque(true);
        btnRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRiwayatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRiwayatMouseExited(evt);
            }
        });
        btnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
            .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAdminLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
            .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAdminLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        jLayeredPanel.add(panelAdmin, "card2");

        panelPetugas.setBackground(new java.awt.Color(255, 255, 255));

        btnTransaksi.setBackground(new java.awt.Color(28, 42, 57));
        btnTransaksi.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setBorder(null);
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.setOpaque(true);
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnBarang1.setBackground(new java.awt.Color(28, 42, 57));
        btnBarang1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnBarang1.setForeground(new java.awt.Color(255, 255, 255));
        btnBarang1.setText("Data Barang");
        btnBarang1.setBorder(null);
        btnBarang1.setContentAreaFilled(false);
        btnBarang1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarang1.setOpaque(true);
        btnBarang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBarang1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBarang1MouseExited(evt);
            }
        });
        btnBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarang1ActionPerformed(evt);
            }
        });

        btnRiwayat1.setBackground(new java.awt.Color(28, 42, 57));
        btnRiwayat1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnRiwayat1.setForeground(new java.awt.Color(255, 255, 255));
        btnRiwayat1.setText("Riwayat");
        btnRiwayat1.setBorder(null);
        btnRiwayat1.setContentAreaFilled(false);
        btnRiwayat1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRiwayat1.setOpaque(true);
        btnRiwayat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRiwayat1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRiwayat1MouseExited(evt);
            }
        });
        btnRiwayat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPetugasLayout = new javax.swing.GroupLayout(panelPetugas);
        panelPetugas.setLayout(panelPetugasLayout);
        panelPetugasLayout.setHorizontalGroup(
            panelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
            .addGroup(panelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPetugasLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(panelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRiwayat1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        panelPetugasLayout.setVerticalGroup(
            panelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
            .addGroup(panelPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPetugasLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnRiwayat1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        jLayeredPanel.add(panelPetugas, "card2");

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelWelcome)
                .addGap(107, 107, 107))
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLeftLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLeftLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(judulAplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLeftLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelDeveloper)))
                    .addGroup(panelLeftLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(labelJam, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(judulAplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDeveloper)
                .addGap(26, 26, 26)
                .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(labelJam, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                    .addContainerGap(213, Short.MAX_VALUE)
                    .addComponent(jLayeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(216, Short.MAX_VALUE)))
        );

        panelRight.setBackground(new java.awt.Color(28, 42, 57));

        panelUser.setBackground(new java.awt.Color(26, 177, 136));
        panelUser.setMinimumSize(new java.awt.Dimension(199, 77));

        labelCountUser.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        labelCountUser.setForeground(new java.awt.Color(255, 255, 255));
        labelCountUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCountUser.setText("counter");
        labelCountUser.setToolTipText("");

        labelJumUser.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelJumUser.setForeground(new java.awt.Color(255, 255, 255));
        labelJumUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelJumUser.setText("Jumlah User");
        labelJumUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelJumUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCountUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelUserLayout.createSequentialGroup()
                .addComponent(labelJumUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCountUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJumUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTransaksi.setBackground(new java.awt.Color(26, 177, 136));
        panelTransaksi.setMinimumSize(new java.awt.Dimension(199, 77));

        labelTransaksi.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        labelTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        labelTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTransaksi.setText("Counter");
        labelTransaksi.setMinimumSize(new java.awt.Dimension(199, 77));

        labelJumTransaksi.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelJumTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        labelJumTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelJumTransaksi.setText("Total Penjualan");
        labelJumTransaksi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelJumTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelJumTransaksi.setMinimumSize(new java.awt.Dimension(199, 77));

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addComponent(labelJumTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJumTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelJmlTransaksi.setBackground(new java.awt.Color(26, 177, 136));
        panelJmlTransaksi.setMinimumSize(new java.awt.Dimension(199, 77));

        labelJmlTransaksi.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        labelJmlTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        labelJmlTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJmlTransaksi.setText("counter");
        labelJmlTransaksi.setMinimumSize(new java.awt.Dimension(199, 77));

        tabeltotTransaksi.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tabeltotTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        tabeltotTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tabeltotTransaksi.setText("Jumlah Transaksi");
        tabeltotTransaksi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tabeltotTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tabeltotTransaksi.setMinimumSize(new java.awt.Dimension(199, 77));

        javax.swing.GroupLayout panelJmlTransaksiLayout = new javax.swing.GroupLayout(panelJmlTransaksi);
        panelJmlTransaksi.setLayout(panelJmlTransaksiLayout);
        panelJmlTransaksiLayout.setHorizontalGroup(
            panelJmlTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJmlTransaksiLayout.createSequentialGroup()
                .addComponent(tabeltotTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelJmlTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJmlTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJmlTransaksiLayout.setVerticalGroup(
            panelJmlTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJmlTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJmlTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabeltotTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTerjual.setBackground(new java.awt.Color(26, 177, 136));
        panelTerjual.setMinimumSize(new java.awt.Dimension(199, 77));

        labelTerjual.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        labelTerjual.setForeground(new java.awt.Color(255, 255, 255));
        labelTerjual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTerjual.setText("counter");

        labelTextTerjual.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelTextTerjual.setForeground(new java.awt.Color(255, 255, 255));
        labelTextTerjual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTextTerjual.setText("Barang Terjual");
        labelTextTerjual.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelTextTerjual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTerjualLayout = new javax.swing.GroupLayout(panelTerjual);
        panelTerjual.setLayout(panelTerjualLayout);
        panelTerjualLayout.setHorizontalGroup(
            panelTerjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTerjualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTerjual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTerjualLayout.createSequentialGroup()
                .addComponent(labelTextTerjual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTerjualLayout.setVerticalGroup(
            panelTerjualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerjualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTextTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelJmlTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTerjual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(448, 448, 448))
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelJmlTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserMouseExited

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
//        TODO add your handling code here: 
        try {
            new DataUserJFrame().setVisible(true);
            dispose();
            
         } catch (ParseException ex) {
             Logger.getLogger(MenuJFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarangMouseEntered

    private void btnBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarangMouseExited

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        try{
            new DataBarangJFrame().setVisible(true);
            dispose();
        }catch(ParseException ex){
            Logger.getLogger(MenuJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnRiwayatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRiwayatMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRiwayatMouseEntered

    private void btnRiwayatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRiwayatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRiwayatMouseExited

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
         try {
             // TODO add your handling code here:
             new RiwayatJFrame().setVisible(true);
              dispose();
         } catch (ParseException ex) {
             Logger.getLogger(MenuJFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
           
        
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutMouseExited

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Anda ingin Log Out?", "Alert!",JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(opsi== JOptionPane.YES_OPTION){
            dispose();
            new Login().setVisible(true);
        }
        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        try{
            new TransaksiJFrame().setVisible(true);
            dispose();
        }catch(ParseException ex){
            Logger.getLogger(MenuJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnBarang1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarang1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarang1MouseEntered

    private void btnBarang1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarang1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarang1MouseExited

    private void btnBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarang1ActionPerformed
        // TODO add your handling code here:
        try{
            new DataBarangJFrame().setVisible(true);
            dispose();
        }catch(ParseException ex){
            Logger.getLogger(MenuJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBarang1ActionPerformed

    private void btnRiwayat1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRiwayat1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRiwayat1MouseEntered

    private void btnRiwayat1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRiwayat1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRiwayat1MouseExited

    private void btnRiwayat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayat1ActionPerformed
        // TODO add your handling code here:
        try {
             // TODO add your handling code here:
             new RiwayatJFrame().setVisible(true);
              dispose();
         } catch (ParseException ex) {
             Logger.getLogger(MenuJFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
             
    }//GEN-LAST:event_btnRiwayat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnBarang1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnRiwayat1;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnUser;
    private javax.swing.JLayeredPane jLayeredPanel;
    private javax.swing.JLabel judulAplikasi;
    private javax.swing.JLabel labelCountUser;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelJam;
    private javax.swing.JLabel labelJmlTransaksi;
    private javax.swing.JLabel labelJumTransaksi;
    private javax.swing.JLabel labelJumUser;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTerjual;
    private javax.swing.JLabel labelTextTerjual;
    private javax.swing.JLabel labelTransaksi;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JLabel panelDeveloper;
    private javax.swing.JPanel panelJmlTransaksi;
    private javax.swing.JPanel panelLeft;
    protected javax.swing.JPanel panelPetugas;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelTerjual;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JPanel panelUser;
    private javax.swing.JLabel tabeltotTransaksi;
    // End of variables declaration//GEN-END:variables

    private void setJam(JLabel jLabel1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
